// src/items.js
// Single source of truth for all scavenger hunt items.
// Edit this file to update items, point values, or types before the event.
//
// item_type values:
//   "standard"  — regular hunt items, displayed in the main list
//   "sponsor"   — sponsor spotlight items, displayed in a distinct section

const items = [
{ id: "animal_tracks", label: "Animal Tracks or Evidence of an animal (no dogs)", points: 15, item_type: "standard" },
{ id: "plants_bloom", label: "Plants in bloom", points: 25, item_type: "standard" },
{ id: "terrain_trap", label: "Terrain Trap", points: 5, item_type: "standard" },
{ id: "pocket_bacon", label: "Pocket bacon on the skin track", points: 10, item_type: "standard" },
{ id: "switchbacks", label: "Switchbacks on the skin track", points: 5, item_type: "standard" },
{ id: "kickturns", label: "Kickturns", points: 5, item_type: "standard" },
{ id: "layers_snowpack", label: "Layers in the snow pack", points: 10, item_type: "standard" },
{ id: "snowpack_depth", label: "Snowpack depth (probe the snow)", points: 5, item_type: "standard" },
{ id: "aspen_grove", label: "Touring through Aspen Grove", points: 5, item_type: "standard" },
{ id: "beacon_search", label: "Beacon search", points: 10, item_type: "standard" },
{ id: "clean_litter", label: "Clean up some litter", points: 35, item_type: "standard" },
{ id: "transition", label: "Transition from tour mode to ski/snowboard mode", points: 5, item_type: "standard" },
{ id: "wind_loaded", label: "Wind loaded area", points: 5, item_type: "standard" },
{ id: "sastrugi", label: "Sastrugi: wind sculpted snow", points: 5, item_type: "standard" },
{ id: "snowman", label: "A snow(wo)man enjoying the sunshine", points: 10, item_type: "standard" },
{ id: "good_turns", label: "Evidence of GOOD & FUN turns on a slope", points: 10, item_type: "standard" },
{ id: "vntrbirds_logo", label: "The VNTRbirds logo in the backcountry", points: 25, item_type: "standard" },
{ id: "karaoke", label: "Backcountry Karaoke (find a microphone + belt it out)", points: 40, item_type: "standard" },
{ id: "smores_stick", label: "A great stick to cook s'mores during our bonfire Friday!", points: 10, item_type: "standard" },
{ id: "view_top", label: "View from top of skin track before dropping in", points: 10, item_type: "standard" },
{ id: "huge_smiles", label: "Huge smiles from an awesome tour or descent - selfies welcome!", points: 10, item_type: "standard" },
{ id: "hype_video", label: "Video of why you're hyped to be at Venture Out! - tag us on IG!", points: 75, item_type: "standard" },
{ id: "trail_markers", label: "Trail markers", points: 15, item_type: "standard" },
{ id: "pallas_splitboard", label: "Pallas splitboard getting some turns", points: 10, item_type: "standard" },
{ id: "fallen_trees", label: "Fallen trees", points: 5, item_type: "standard" },
{ id: "reviewing_map", label: "Reviewing a map", points: 10, item_type: "standard" },
{ id: "dog_backcountry", label: "Find a dog in the backcountry", points: 5, item_type: "standard" },
{ id: "onesie", label: "A picture of someone wearing a onesie", points: 30, item_type: "standard" },
{ id: "tutu", label: "Neon tutu at the GLOW Dance Party (or anywhere, really)", points: 35, item_type: "standard" },
{ id: "hydrated", label: "Evidence of staying hydrated before the Distillery Happy Hour", points: 20, item_type: "standard" },
{ id: "pine_trees", label: "A tour through pine trees", points: 5, item_type: "standard" },
{ id: "old_cabin", label: "An old cabin", points: 10, item_type: "standard" },
{ id: "avalanche_evidence", label: "Evidence of a past avalanche/slide", points: 25, item_type: "standard" },
{ id: "selfie_madi", label: "Selfie with Madi from Kari Traa", points: 10, item_type: "standard" },
{ id: "popcorn", label: "Munching popcorn", points: 5, item_type: "standard" },
{ id: "snowball", label: "Throwing a snowball", points: 5, item_type: "standard" },
{ id: "beautiful", label: "Something you think is beautiful", points: 5, item_type: "standard" },
{ id: "high_fives", label: "High Fives in the backcountry", points: 10, item_type: "standard" },
{ id: "snow_angels", label: "Snow Angels in the backcountry", points: 5, item_type: "standard" },
{ id: "selfie_instructor", label: "Selfie with your instructor on a guided tour", points: 30, item_type: "standard" },
{ id: "sunrise", label: "The sunrise on a tour", points: 40, item_type: "standard" },
{ id: "ripping_skins", label: "Ripping skins while still in bindings", points: 10, item_type: "standard" },
{ id: "soaking_sun", label: "Soaking up the sun near the river", points: 10, item_type: "standard" },
{ id: "waxing", label: "Waxing your equipment", points: 10, item_type: "standard" },
{ id: "yoga_olas", label: "Warrior pose at the YOGA OLAS session", points: 25, item_type: "standard" },
{ id: "apres", label: "Cheers at Après Hour with Breckenridge Distillery or Best Day Brewing (n/a options available)", points: 10, item_type: "standard" },
{ id: "birds", label: "Birds in the backcountry (you can be creative)", points: 10, item_type: "standard" },
{ id: "avy_forecast", label: "Checking the Avalanche Forecast", points: 10, item_type: "standard" },
{ id: "smores", label: "Toasting up s'mores", points: 5, item_type: "standard" },
{ id: "saltations", label: "Saltations: moving snow", points: 10, item_type: "standard" },
{ id: "ski_tuck", label: "10/10 Ski Tuck", points: 5, item_type: "standard" },
{ id: "coffee_topo", label: "Enjoying a coffee at Coffee by Topo", points: 25, item_type: "standard" },
{ id: "woo_girl", label: "Being a 'woo girl' (evidence of having the best run and letting out a woo!)", points: 5, item_type: "standard" },
{ id: "hype_sign", label: "A sign hyping you up", points: 15, item_type: "standard" },
{ id: "goggle_tan", label: "Photo of someone with a goggle tan (ask permission)", points: 10, item_type: "standard" },
{ id: "ski_strap", label: "Using a ski strap in a functional way", points: 20, item_type: "standard" },
{ id: "skin_care", label: "Practicing skin care (either climbing skins or facial)", points: 10, item_type: "standard" },
{ id: "glopping", label: "Glopping on your skins (when snow builds and sticks to your climbing skins)", points: 35, item_type: "standard" },
{ id: "coordinated_dance", label: "Video of a coordinated dance with your partner", points: 50, item_type: "standard" },
{ id: "continental_divide", label: "Photo with the Continental Divide sign", points: 20, item_type: "standard" },
{ id: "snowpack_talk", label: "Your most attentive face at Janine's State of the Snowpack talk", points: 15, item_type: "standard" },
{ id: "film_festival", label: "Most dramatic reaction shot at No Man's Land Film Festival", points: 20, item_type: "standard" },
{ id: "robins_breakfast", label: "First bite (or plate) at Robin's catered breakfast", points: 10, item_type: "standard" },
{ id: "sponsor_karitraa", label: "Kari Traa — Embroidered beanie from the workshop", points: 50, item_type: "sponsor" },
{ id: "sponsor_skilikeagirl", label: "Ski Like a Girl — SWAG in the wild", points: 50, item_type: "sponsor" },
{ id: "sponsor_rmu", label: "RMU — Skis on the skin track", points: 50, item_type: "sponsor" },
{ id: "sponsor_backcountryready", label: "Backcountry Ready — What's in your first aid kit, or a splint or sling practice", points: 50, item_type: "sponsor" },
{ id: "sponsor_bestday", label: "Best Day Brewing — At the trailhead", points: 50, item_type: "sponsor" },
{ id: "sponsor_beacon", label: "Beacon Guidebooks — Map you built at the Mapping Workshop", points: 50, item_type: "sponsor" },
{ id: "sponsor_salidamtn", label: "Salida Mountain Sports — Picking up demo gear", points: 50, item_type: "sponsor" },
{ id: "sponsor_coalition", label: "Coalition Snow — At the film festival or shredding on skis or a snowboard (they're raffling some!)", points: 50, item_type: "sponsor" },
{ id: "sponsor_breckmassage", label: "Breck Mtn Massage — Treating yourself to a massage", points: 50, item_type: "sponsor" },
{ id: "sponsor_breckenridge", label: "Breckenridge Distillery — Mountain Shot Pouch on an adventure", points: 50, item_type: "sponsor" },
{ id: "sponsor_glitter", label: "Sex Plants Rock+Roll — DIY face mask or glitter creation from the workshop", points: 50, item_type: "sponsor" },
{ id: "sponsor_titsdeep", label: "Tits Deep — Pic or selfie in deep snow", points: 50, item_type: "sponsor" },
{ id: "sponsor_sunshine", label: "Sunshine Sauna — Post-tour recovery", points: 50, item_type: "sponsor" },
];

export default items;
